### ISSUE TITLE
architecture big data platform

### ISSUE THREAD

**Issue by macroldj** [macroldj/architecture#27]
1. 基于本地主机的 -> develop envrionment

**Comment by macroldj** [comment]
1. 基于本地主机的 -> develop envrionment

**Comment by macroldj** [comment]
```yaml
apiVersion: v1
kind: ReplicationController
metadata:
  name: mysql-rc
  labels:
    name: mysql-rc
spec:
  replicas: 1
  selector:
    name: mysql-pod
  template:
    metadata:
      labels: 
        name: mysql-pod
    spec:
      containers:
      - name: mysql
        image: mysql
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 3306
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: "mysql"
```
